# Generated by Django 4.2.6 on 2023-11-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_club', '0003_alter_event_table_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
